from typing import Self
from pydantic import ModelWrapValidatorHandler, PrivateAttr, model_validator
from datetime import time
from typing import Any
from uuid import UUID
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, NaiveDatetime

class AvailableVideoSeason(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    season_num: str | Any = Field(None, alias='seasonNum', union_mode='left_to_right')
    total_count: int | Any = Field(None, alias='totalCount', union_mode='left_to_right')
    premium_count: int | Any = Field(None, alias='premiumCount', union_mode='left_to_right')
    clips_count: int | Any = Field(None, alias='clipsCount', union_mode='left_to_right')
    delay_count: int | Any = Field(None, alias='delayCount', union_mode='left_to_right')
    season_premiere_date: Any | None = Field(None, alias='seasonPremiereDate')
    season_premiere_date_epoch: Any | None = Field(None, alias='seasonPremiereDateEpoch')
    season_finale_date: Any | None = Field(None, alias='seasonFinaleDate')
    season_finale_date_epoch: Any | None = Field(None, alias='seasonFinaleDateEpoch')

class ShowAssets(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    filepath_apple_airplay: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_mobile_endcard: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_show_page_header: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_title_logo_regular: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_video_endcard_show_image: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_title_logo_left: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_title_logo_center: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_apple_centered_background: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_show_hero_landscape: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_ott_hd_show_image_overhang: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_apple_content_logo_polychromatic: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_show_browse_poster: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_show_hero_regular: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_show_hero_compact: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_show_hero_portrait: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_apple_cover_artwork_horizontal: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_title_logo_compact: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_apple_content_logo_monochromatic: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_apple_centered_background_small: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_apple_top_shelf: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_show_poster: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_partner_brand_logo: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_brand_hero: str | Any = Field(default=None, union_mode='left_to_right')

class ThumbnailSetItem(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    height: int | Any = Field(default=None, union_mode='left_to_right')
    width: int | Any = Field(default=None, union_mode='left_to_right')
    asset_type: str | Any = Field(None, alias='assetType', union_mode='left_to_right')
    url: str | Any = Field(default=None, union_mode='left_to_right')

class DownloadCountrySetItem(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    code: str | Any = Field(default=None, union_mode='left_to_right')
    downloadable: bool | Any = Field(default=None, union_mode='left_to_right')

class RegionalRating(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    region: str | Any = Field(default=None, union_mode='left_to_right')
    rating: str | Any = Field(default=None, union_mode='left_to_right')
    disclaimer: Any | None = None
    secondary_descriptors: Any | None = Field(None, alias='secondaryDescriptors')
    subratings: Any | None = None
    consumer_advice: Any | None = Field(None, alias='consumerAdvice')
    rating_icon: Any | None = Field(None, alias='ratingIcon')

class PlaybackEvents(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    end_credit_chapter_time_ms: int | Any = Field(None, alias='endCreditChapterTimeMs', union_mode='left_to_right')
    preview_start_time_ms: Any | None = Field(None, alias='previewStartTimeMs')
    preview_end_time_ms: Any | None = Field(None, alias='previewEndTimeMs')
    open_credit_end_time_ms: Any | None = Field(None, alias='openCreditEndTimeMs')
    open_credit_start_time: Any | None = Field(None, alias='openCreditStartTime')

class ThumbnailSheetSetItem(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    height: int | Any = Field(default=None, union_mode='left_to_right')
    width: int | Any = Field(default=None, union_mode='left_to_right')
    asset_type: str | Any = Field(None, alias='assetType', union_mode='left_to_right')
    url: str | Any = Field(default=None, union_mode='left_to_right')

class MovieContent(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    genre: str | Any = Field(default=None, union_mode='left_to_right')
    status: str | Any = Field(default=None, union_mode='left_to_right')
    field_first_ingest_date: str | Any = Field(None, alias='_firstIngestDate', union_mode='left_to_right')
    expired: bool | Any = Field(default=None, union_mode='left_to_right')
    show_page_url: str | Any = Field(None, alias='showPageUrl', union_mode='left_to_right')
    cbs_show_id: int | Any = Field(None, alias='cbsShowId', union_mode='left_to_right')
    primary_category: str | Any = Field(None, alias='primaryCategory', union_mode='left_to_right')
    primary_category_name: str | Any = Field(None, alias='primaryCategoryName', union_mode='left_to_right')
    edit_date: int | Any = Field(None, alias='editDate', union_mode='left_to_right')
    field_edit_date: str | Any = Field(None, alias='_editDate', union_mode='left_to_right')
    field_last_modified_date: str | Any = Field(None, alias='_lastModifiedDate', union_mode='left_to_right')
    ingest_date: int | Any = Field(None, alias='ingestDate', union_mode='left_to_right')
    air_date: int | Any = Field(None, alias='airDate', union_mode='left_to_right')
    description: str | Any = Field(default=None, union_mode='left_to_right')
    short_description: str | Any = Field(None, alias='shortDescription', union_mode='left_to_right')
    pub_date: int | Any = Field(None, alias='pubDate', union_mode='left_to_right')
    label: str | Any = Field(default=None, union_mode='left_to_right')
    url: str | Any = Field(default=None, union_mode='left_to_right')
    asset_type: str | Any = Field(None, alias='assetType', union_mode='left_to_right')
    first_ingest_date: int | Any = Field(None, alias='firstIngestDate', union_mode='left_to_right')
    category: str | Any = Field(default=None, union_mode='left_to_right')
    top_level_category: str | Any = Field(None, alias='topLevelCategory', union_mode='left_to_right')
    full_episode: bool | Any = Field(None, alias='fullEpisode', union_mode='left_to_right')
    exclusive: bool | Any = Field(default=None, union_mode='left_to_right')
    content_id: str | Any = Field(None, alias='contentId', union_mode='left_to_right')
    title: str | Any = Field(default=None, union_mode='left_to_right')
    field_ingest_date: str | Any = Field(None, alias='_ingestDate', union_mode='left_to_right')
    episode_num: str | Any = Field(None, alias='episodeNum', union_mode='left_to_right')
    field_pub_date: str | Any = Field(None, alias='_pubDate', union_mode='left_to_right')
    season_num: str | Any = Field(None, alias='seasonNum', union_mode='left_to_right')
    brand: str | Any = Field(default=None, union_mode='left_to_right')
    child_content_id: str | Any = Field(None, alias='childContentId', union_mode='left_to_right')
    sizzle_id: str | Any = Field(None, alias='sizzleId', union_mode='left_to_right')
    series_title: str | Any = Field(None, alias='seriesTitle', union_mode='left_to_right')
    field_air_date: str | Any = Field(None, alias='_airDate', union_mode='left_to_right')
    duration: int | Any = Field(default=None, union_mode='left_to_right')
    last_modified_date: int | Any = Field(None, alias='lastModifiedDate', union_mode='left_to_right')
    rating: str | Any = Field(default=None, union_mode='left_to_right')
    device_type: str | Any = Field(None, alias='deviceType', union_mode='left_to_right')
    thumbnail: str | Any = Field(default=None, union_mode='left_to_right')
    amazon_esturl: str | Any = Field(None, alias='amazonESTURL', union_mode='left_to_right')
    itunes_esturl: str | Any = Field(None, alias='itunesESTURL', union_mode='left_to_right')
    expiration_date: int | Any = Field(None, alias='expirationDate', union_mode='left_to_right')
    field_expiration_date: str | Any = Field(None, alias='_expirationDate', union_mode='left_to_right')
    field_pub_date_iso: AwareDatetime | Any = Field(None, alias='_pubDateISO', union_mode='left_to_right')
    field_air_date_iso: AwareDatetime | Any = Field(None, alias='_airDateISO', union_mode='left_to_right')
    subscription_level: str | Any = Field(None, alias='subscriptionLevel', union_mode='left_to_right')
    media_available_date: AwareDatetime | Any = Field(None, alias='mediaAvailableDate', union_mode='left_to_right')
    media_available_date_epoch: int | Any = Field(None, alias='mediaAvailableDateEpoch', union_mode='left_to_right')
    is_live: bool | Any = Field(None, alias='isLive', union_mode='left_to_right')
    cms_account_id: str | Any = Field(None, alias='cmsAccountId', union_mode='left_to_right')
    apple_watch_list_show_key: str | Any = Field(None, alias='appleWatchListShowKey', union_mode='left_to_right')
    is_protected: bool | Any = Field(None, alias='isProtected', union_mode='left_to_right')
    media_type: str | Any = Field(None, alias='mediaType', union_mode='left_to_right')
    exclude_nielsen_tracking: bool | Any = Field(None, alias='excludeNielsenTracking', union_mode='left_to_right')
    end_credits_chapter_time: time | Any = Field(None, alias='endCreditsChapterTime', union_mode='left_to_right')
    thumbnail_set: list[ThumbnailSetItem] | Any = Field(None, alias='thumbnailSet', union_mode='left_to_right')
    download_country_set: list[DownloadCountrySetItem] | Any = Field(None, alias='downloadCountrySet', union_mode='left_to_right')
    regional_ratings: list[RegionalRating] | Any = Field(None, alias='regionalRatings', union_mode='left_to_right')
    premium_features: list[str] | Any = Field(None, alias='premiumFeatures', union_mode='left_to_right')
    video_properties: list[str] | Any = Field(None, alias='videoProperties', union_mode='left_to_right')
    aspect_ratio: str | Any = Field(None, alias='aspectRatio', union_mode='left_to_right')
    external_id: str | Any = Field(None, alias='externalId', union_mode='left_to_right')
    available_for_profile_types: list[str] | Any = Field(None, alias='availableForProfileTypes', union_mode='left_to_right')
    playback_events: PlaybackEvents | Any = Field(None, alias='playbackEvents', union_mode='left_to_right')
    embeddable: str | Any = Field(default=None, union_mode='left_to_right')
    copyright: str | Any = Field(default=None, union_mode='left_to_right')
    add_ons: list[Any] | Any = Field(None, alias='addOns', union_mode='left_to_right')
    regional_audio_exclude_languages: list[Any] | Any = Field(None, alias='regionalAudioExcludeLanguages', union_mode='left_to_right')
    regional_text_exclude_languages: list[Any] | Any = Field(None, alias='regionalTextExcludeLanguages', union_mode='left_to_right')
    original_release_year: int | Any = Field(None, alias='originalReleaseYear', union_mode='left_to_right')
    tmsseries_id: str | Any = Field(None, alias='tmsseriesID', union_mode='left_to_right')
    tmsprogram_id: str | Any = Field(None, alias='tmsprogramID', union_mode='left_to_right')
    is_content_accessible_in_can: bool | Any = Field(None, alias='isContentAccessibleInCAN', union_mode='left_to_right')
    thumbnail_sheet_set: list[ThumbnailSheetSetItem] | Any = Field(None, alias='thumbnailSheetSet', union_mode='left_to_right')
    v_tag: str | Any = Field(None, alias='vTag', union_mode='left_to_right')
    is_product_placement: bool | Any = Field(None, alias='isProductPlacement', union_mode='left_to_right')

class PlaybackEvents1(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    end_credit_chapter_time_ms: Any | None = Field(None, alias='endCreditChapterTimeMs')
    preview_start_time_ms: Any | None = Field(None, alias='previewStartTimeMs')
    preview_end_time_ms: Any | None = Field(None, alias='previewEndTimeMs')
    open_credit_end_time_ms: Any | None = Field(None, alias='openCreditEndTimeMs')
    open_credit_start_time: Any | None = Field(None, alias='openCreditStartTime')

class TrailerContent(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    genre: str | Any = Field(default=None, union_mode='left_to_right')
    status: str | Any = Field(default=None, union_mode='left_to_right')
    field_first_ingest_date: str | Any = Field(None, alias='_firstIngestDate', union_mode='left_to_right')
    expired: bool | Any = Field(default=None, union_mode='left_to_right')
    show_page_url: str | Any = Field(None, alias='showPageUrl', union_mode='left_to_right')
    cbs_show_id: int | Any = Field(None, alias='cbsShowId', union_mode='left_to_right')
    primary_category: str | Any = Field(None, alias='primaryCategory', union_mode='left_to_right')
    primary_category_name: str | Any = Field(None, alias='primaryCategoryName', union_mode='left_to_right')
    edit_date: int | Any = Field(None, alias='editDate', union_mode='left_to_right')
    field_edit_date: str | Any = Field(None, alias='_editDate', union_mode='left_to_right')
    field_last_modified_date: str | Any = Field(None, alias='_lastModifiedDate', union_mode='left_to_right')
    ingest_date: int | Any = Field(None, alias='ingestDate', union_mode='left_to_right')
    air_date: int | Any = Field(None, alias='airDate', union_mode='left_to_right')
    description: str | Any = Field(default=None, union_mode='left_to_right')
    short_description: str | Any = Field(None, alias='shortDescription', union_mode='left_to_right')
    pub_date: int | Any = Field(None, alias='pubDate', union_mode='left_to_right')
    label: str | Any = Field(default=None, union_mode='left_to_right')
    video_page_url: str | Any = Field(None, alias='videoPageUrl', union_mode='left_to_right')
    url: str | Any = Field(default=None, union_mode='left_to_right')
    asset_type: str | Any = Field(None, alias='assetType', union_mode='left_to_right')
    first_ingest_date: int | Any = Field(None, alias='firstIngestDate', union_mode='left_to_right')
    category: str | Any = Field(default=None, union_mode='left_to_right')
    top_level_category: str | Any = Field(None, alias='topLevelCategory', union_mode='left_to_right')
    full_episode: bool | Any = Field(None, alias='fullEpisode', union_mode='left_to_right')
    exclusive: bool | Any = Field(default=None, union_mode='left_to_right')
    content_id: str | Any = Field(None, alias='contentId', union_mode='left_to_right')
    title: str | Any = Field(default=None, union_mode='left_to_right')
    field_ingest_date: str | Any = Field(None, alias='_ingestDate', union_mode='left_to_right')
    episode_num: str | Any = Field(None, alias='episodeNum', union_mode='left_to_right')
    field_pub_date: str | Any = Field(None, alias='_pubDate', union_mode='left_to_right')
    season_num: str | Any = Field(None, alias='seasonNum', union_mode='left_to_right')
    brand: str | Any = Field(default=None, union_mode='left_to_right')
    child_content_id: str | Any = Field(None, alias='childContentId', union_mode='left_to_right')
    sizzle_id: str | Any = Field(None, alias='sizzleId', union_mode='left_to_right')
    pid: UUID | str | Any = Field(default=None, union_mode='left_to_right')
    series_title: str | Any = Field(None, alias='seriesTitle', union_mode='left_to_right')
    field_air_date: str | Any = Field(None, alias='_airDate', union_mode='left_to_right')
    duration: int | Any = Field(default=None, union_mode='left_to_right')
    last_modified_date: int | Any = Field(None, alias='lastModifiedDate', union_mode='left_to_right')
    rating: str | Any = Field(default=None, union_mode='left_to_right')
    device_type: str | Any = Field(None, alias='deviceType', union_mode='left_to_right')
    thumbnail: str | Any = Field(default=None, union_mode='left_to_right')
    amazon_esturl: str | Any = Field(None, alias='amazonESTURL', union_mode='left_to_right')
    itunes_esturl: str | Any = Field(None, alias='itunesESTURL', union_mode='left_to_right')
    streaming_url: str | Any = Field(None, alias='streamingUrl', union_mode='left_to_right')
    expiration_date: int | Any = Field(None, alias='expirationDate', union_mode='left_to_right')
    field_expiration_date: str | Any = Field(None, alias='_expirationDate', union_mode='left_to_right')
    field_pub_date_iso: AwareDatetime | Any = Field(None, alias='_pubDateISO', union_mode='left_to_right')
    field_air_date_iso: AwareDatetime | Any = Field(None, alias='_airDateISO', union_mode='left_to_right')
    player_loc_url: str | Any = Field(None, alias='playerLocUrl', union_mode='left_to_right')
    subscription_level: str | Any = Field(None, alias='subscriptionLevel', union_mode='left_to_right')
    media_available_date: AwareDatetime | Any = Field(None, alias='mediaAvailableDate', union_mode='left_to_right')
    media_available_date_epoch: int | Any = Field(None, alias='mediaAvailableDateEpoch', union_mode='left_to_right')
    closed_caption_url: str | Any = Field(None, alias='closedCaptionUrl', union_mode='left_to_right')
    is_live: bool | Any = Field(None, alias='isLive', union_mode='left_to_right')
    cms_account_id: str | Any = Field(None, alias='cmsAccountId', union_mode='left_to_right')
    apple_watch_list_show_key: str | Any = Field(None, alias='appleWatchListShowKey', union_mode='left_to_right')
    is_protected: bool | Any = Field(None, alias='isProtected', union_mode='left_to_right')
    media_type: str | Any = Field(None, alias='mediaType', union_mode='left_to_right')
    exclude_nielsen_tracking: bool | Any = Field(None, alias='excludeNielsenTracking', union_mode='left_to_right')
    end_credits_chapter_time: str | Any = Field(None, alias='endCreditsChapterTime', union_mode='left_to_right')
    thumbnail_set: list[ThumbnailSetItem] | Any = Field(None, alias='thumbnailSet', union_mode='left_to_right')
    download_country_set: list[Any] | Any = Field(None, alias='downloadCountrySet', union_mode='left_to_right')
    regional_ratings: list[RegionalRating] | Any = Field(None, alias='regionalRatings', union_mode='left_to_right')
    premium_features: list[str] | Any = Field(None, alias='premiumFeatures', union_mode='left_to_right')
    video_properties: list[str] | Any = Field(None, alias='videoProperties', union_mode='left_to_right')
    aspect_ratio: str | Any = Field(None, alias='aspectRatio', union_mode='left_to_right')
    external_id: str | Any = Field(None, alias='externalId', union_mode='left_to_right')
    available_for_profile_types: list[str] | Any = Field(None, alias='availableForProfileTypes', union_mode='left_to_right')
    playback_events: PlaybackEvents1 | Any = Field(None, alias='playbackEvents', union_mode='left_to_right')
    embeddable: str | Any = Field(default=None, union_mode='left_to_right')
    copyright: str | Any = Field(default=None, union_mode='left_to_right')
    add_ons: list[Any] | Any = Field(None, alias='addOns', union_mode='left_to_right')
    regional_audio_exclude_languages: list[Any] | Any = Field(None, alias='regionalAudioExcludeLanguages', union_mode='left_to_right')
    regional_text_exclude_languages: list[Any] | Any = Field(None, alias='regionalTextExcludeLanguages', union_mode='left_to_right')
    original_release_year: int | Any = Field(None, alias='originalReleaseYear', union_mode='left_to_right')
    tmsseries_id: str | Any = Field(None, alias='tmsseriesID', union_mode='left_to_right')
    tmsprogram_id: str | Any = Field(None, alias='tmsprogramID', union_mode='left_to_right')
    is_content_accessible_in_can: bool | Any = Field(None, alias='isContentAccessibleInCAN', union_mode='left_to_right')
    thumbnail_sheet_set: list[ThumbnailSheetSetItem] | Any = Field(None, alias='thumbnailSheetSet', union_mode='left_to_right')
    v_tag: str | Any = Field(None, alias='vTag', union_mode='left_to_right')
    is_product_placement: bool | Any = Field(None, alias='isProductPlacement', union_mode='left_to_right')

class MovieAssets(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    filepath_movie_keep_watching: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_movie_poster: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_title_logo_regular: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_movie_logo: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_movie_hero_regular: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_movie_hero: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_title_logo_left: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_partner_movie_poster: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_movie_hero_compact: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_title_logo_center: str | Any = Field(default=None, union_mode='left_to_right')
    filepath_title_logo_compact: str | Any = Field(default=None, union_mode='left_to_right')

class Content(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    hub_id: int | Any = Field(None, alias='hubId', union_mode='left_to_right')
    title: str | Any = Field(default=None, union_mode='left_to_right')
    hub_slug: str | Any = Field(None, alias='hubSlug', union_mode='left_to_right')
    type: str | Any = Field(default=None, union_mode='left_to_right')
    hub_items: Any | None = Field(None, alias='hubItems')
    page_type: str | Any = Field(None, alias='pageType', union_mode='left_to_right')
    region: str | Any = Field(default=None, union_mode='left_to_right')
    locale: str | Any = Field(default=None, union_mode='left_to_right')
    user_state: list[str] | Any = Field(None, alias='userState', union_mode='left_to_right')
    live_on_date: int | Any = Field(None, alias='liveOnDate', union_mode='left_to_right')
    variant_key: Any | None = Field(None, alias='variantKey')
    show_id: int | Any = Field(None, alias='showId', union_mode='left_to_right')
    about: str | Any = Field(default=None, union_mode='left_to_right')
    show_title: str | Any = Field(None, alias='showTitle', union_mode='left_to_right')
    content_type: str | Any = Field(None, alias='contentType', union_mode='left_to_right')
    show_path: str | Any = Field(None, alias='showPath', union_mode='left_to_right')
    tune_in_time: str | Any = Field(None, alias='tuneInTime', union_mode='left_to_right')
    premium_features: list[Any] | Any = Field(None, alias='premiumFeatures', union_mode='left_to_right')
    category: str | Any = Field(default=None, union_mode='left_to_right')
    available_video_seasons: list[AvailableVideoSeason] | Any = Field(None, alias='availableVideoSeasons', union_mode='left_to_right')
    show_assets: ShowAssets | Any = Field(None, alias='showAssets', union_mode='left_to_right')
    callbacks: dict[str, Any] | Any = Field(default=None, union_mode='left_to_right')
    rating: str | list[str] | Any = Field(default=None, union_mode='left_to_right')
    is_content_accessible_in_cms: bool | Any = Field(None, alias='isContentAccessibleInCMS', union_mode='left_to_right')
    required_add_ons: list[Any] | Any = Field(None, alias='requiredAddOns', union_mode='left_to_right')
    is_after_hours: bool | Any = Field(None, alias='isAfterHours', union_mode='left_to_right')
    is_kids_content: bool | Any = Field(None, alias='isKidsContent', union_mode='left_to_right')
    cast_names: list[str] | Any = Field(None, alias='castNames', union_mode='left_to_right')
    sub_video_starting_point_cta: str | Any = Field(None, alias='subVideoStartingPointCTA', union_mode='left_to_right')
    genre: str | Any = Field(default=None, union_mode='left_to_right')
    unified_genre: list[str] | Any = Field(None, alias='unifiedGenre', union_mode='left_to_right')
    video_preview_url: str | Any = Field(None, alias='videoPreviewURL', union_mode='left_to_right')
    id: int | Any = Field(default=None, union_mode='left_to_right')
    content_id: str | Any = Field(None, alias='contentId', union_mode='left_to_right')
    trailer_content_id: str | Any = Field(None, alias='trailerContentId', union_mode='left_to_right')
    movie_content: MovieContent | Any = Field(None, alias='movieContent', union_mode='left_to_right')
    trailer_content: TrailerContent | Any = Field(None, alias='trailerContent', union_mode='left_to_right')
    movie_assets: MovieAssets | Any = Field(None, alias='movieAssets', union_mode='left_to_right')
    is_movie_available: bool | Any = Field(None, alias='isMovieAvailable', union_mode='left_to_right')
    first_available_date: AwareDatetime | Any = Field(None, alias='firstAvailableDate', union_mode='left_to_right')
    league_id: int | Any = Field(None, alias='leagueId', union_mode='left_to_right')
    brand_slug: str | Any = Field(None, alias='brandSlug', union_mode='left_to_right')
    show_premiere_date_str: NaiveDatetime | Any = Field(None, alias='showPremiereDateStr', union_mode='left_to_right')

class ItemPem(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    pvr_model: str | Any = Field(None, alias='pvrModel', union_mode='left_to_right')
    draw_id: UUID | Any = Field(None, alias='drawId', union_mode='left_to_right')
    arm_id: UUID | Any = Field(None, alias='armId', union_mode='left_to_right')
    p: str | Any = Field(default=None, union_mode='left_to_right')
    mab_id: str | Any = Field(None, alias='mabId', union_mode='left_to_right')

class WatchListCtaContent(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    content_id: int | str | Any = Field(default=None, union_mode='left_to_right')
    content_type: str | Any = Field(default=None, union_mode='left_to_right')
    title: str | Any = Field(default=None, union_mode='left_to_right')
    series_title: str | Any = Field(default=None, union_mode='left_to_right')
    genre: str | Any = Field(default=None, union_mode='left_to_right')

class Subrating(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    code: str | Any = Field(default=None, union_mode='left_to_right')
    description: str | Any = Field(default=None, union_mode='left_to_right')

class RegionalRating2(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    region: str | Any = Field(default=None, union_mode='left_to_right')
    rating: str | Any = Field(default=None, union_mode='left_to_right')
    disclaimer: Any | None = None
    secondary_descriptors: str | Any = Field(None, alias='secondaryDescriptors', union_mode='left_to_right')
    subratings: list[Subrating] | Any = Field(default=None, union_mode='left_to_right')
    consumer_advice: Any | None = Field(None, alias='consumerAdvice')
    rating_icon: Any | None = Field(None, alias='ratingIcon')

class PlaybackEvents2(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    end_credit_chapter_time_ms: int | Any = Field(None, alias='endCreditChapterTimeMs', union_mode='left_to_right')
    preview_start_time_ms: Any | None = Field(None, alias='previewStartTimeMs')
    preview_end_time_ms: Any | None = Field(None, alias='previewEndTimeMs')
    open_credit_end_time_ms: Any | None = Field(None, alias='openCreditEndTimeMs')
    open_credit_start_time: Any | None = Field(None, alias='openCreditStartTime')

class MovieContent1(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    genre: str | Any = Field(default=None, union_mode='left_to_right')
    status: str | Any = Field(default=None, union_mode='left_to_right')
    field_first_ingest_date: str | Any = Field(None, alias='_firstIngestDate', union_mode='left_to_right')
    expired: bool | Any = Field(default=None, union_mode='left_to_right')
    show_page_url: str | Any = Field(None, alias='showPageUrl', union_mode='left_to_right')
    cbs_show_id: int | Any = Field(None, alias='cbsShowId', union_mode='left_to_right')
    primary_category: str | Any = Field(None, alias='primaryCategory', union_mode='left_to_right')
    primary_category_name: str | Any = Field(None, alias='primaryCategoryName', union_mode='left_to_right')
    edit_date: int | Any = Field(None, alias='editDate', union_mode='left_to_right')
    field_edit_date: str | Any = Field(None, alias='_editDate', union_mode='left_to_right')
    field_last_modified_date: str | Any = Field(None, alias='_lastModifiedDate', union_mode='left_to_right')
    ingest_date: int | Any = Field(None, alias='ingestDate', union_mode='left_to_right')
    air_date: int | Any = Field(None, alias='airDate', union_mode='left_to_right')
    description: str | Any = Field(default=None, union_mode='left_to_right')
    short_description: str | Any = Field(None, alias='shortDescription', union_mode='left_to_right')
    pub_date: int | Any = Field(None, alias='pubDate', union_mode='left_to_right')
    label: str | Any = Field(default=None, union_mode='left_to_right')
    url: str | Any = Field(default=None, union_mode='left_to_right')
    asset_type: str | Any = Field(None, alias='assetType', union_mode='left_to_right')
    first_ingest_date: int | Any = Field(None, alias='firstIngestDate', union_mode='left_to_right')
    category: str | Any = Field(default=None, union_mode='left_to_right')
    top_level_category: str | Any = Field(None, alias='topLevelCategory', union_mode='left_to_right')
    full_episode: bool | Any = Field(None, alias='fullEpisode', union_mode='left_to_right')
    exclusive: bool | Any = Field(default=None, union_mode='left_to_right')
    content_id: str | Any = Field(None, alias='contentId', union_mode='left_to_right')
    title: str | Any = Field(default=None, union_mode='left_to_right')
    field_ingest_date: str | Any = Field(None, alias='_ingestDate', union_mode='left_to_right')
    episode_num: str | Any = Field(None, alias='episodeNum', union_mode='left_to_right')
    field_pub_date: str | Any = Field(None, alias='_pubDate', union_mode='left_to_right')
    season_num: str | Any = Field(None, alias='seasonNum', union_mode='left_to_right')
    brand: str | Any = Field(default=None, union_mode='left_to_right')
    child_content_id: str | Any = Field(None, alias='childContentId', union_mode='left_to_right')
    sizzle_id: str | Any = Field(None, alias='sizzleId', union_mode='left_to_right')
    series_title: str | Any = Field(None, alias='seriesTitle', union_mode='left_to_right')
    field_air_date: str | Any = Field(None, alias='_airDate', union_mode='left_to_right')
    duration: int | Any = Field(default=None, union_mode='left_to_right')
    last_modified_date: int | Any = Field(None, alias='lastModifiedDate', union_mode='left_to_right')
    rating: str | Any = Field(default=None, union_mode='left_to_right')
    device_type: str | Any = Field(None, alias='deviceType', union_mode='left_to_right')
    thumbnail: str | Any = Field(default=None, union_mode='left_to_right')
    amazon_esturl: str | Any = Field(None, alias='amazonESTURL', union_mode='left_to_right')
    itunes_esturl: str | Any = Field(None, alias='itunesESTURL', union_mode='left_to_right')
    expiration_date: int | Any = Field(None, alias='expirationDate', union_mode='left_to_right')
    field_expiration_date: str | Any = Field(None, alias='_expirationDate', union_mode='left_to_right')
    field_pub_date_iso: AwareDatetime | Any = Field(None, alias='_pubDateISO', union_mode='left_to_right')
    field_air_date_iso: AwareDatetime | Any = Field(None, alias='_airDateISO', union_mode='left_to_right')
    subscription_level: str | Any = Field(None, alias='subscriptionLevel', union_mode='left_to_right')
    media_available_date: AwareDatetime | Any = Field(None, alias='mediaAvailableDate', union_mode='left_to_right')
    media_available_date_epoch: int | Any = Field(None, alias='mediaAvailableDateEpoch', union_mode='left_to_right')
    is_live: bool | Any = Field(None, alias='isLive', union_mode='left_to_right')
    cms_account_id: str | Any = Field(None, alias='cmsAccountId', union_mode='left_to_right')
    apple_watch_list_show_key: str | Any = Field(None, alias='appleWatchListShowKey', union_mode='left_to_right')
    is_protected: bool | Any = Field(None, alias='isProtected', union_mode='left_to_right')
    media_type: str | Any = Field(None, alias='mediaType', union_mode='left_to_right')
    exclude_nielsen_tracking: bool | Any = Field(None, alias='excludeNielsenTracking', union_mode='left_to_right')
    end_credits_chapter_time: time | Any = Field(None, alias='endCreditsChapterTime', union_mode='left_to_right')
    thumbnail_set: list[ThumbnailSetItem] | Any = Field(None, alias='thumbnailSet', union_mode='left_to_right')
    download_country_set: list[DownloadCountrySetItem] | Any = Field(None, alias='downloadCountrySet', union_mode='left_to_right')
    regional_ratings: list[RegionalRating2] | Any = Field(None, alias='regionalRatings', union_mode='left_to_right')
    premium_features: list[str] | Any = Field(None, alias='premiumFeatures', union_mode='left_to_right')
    video_properties: list[str] | Any = Field(None, alias='videoProperties', union_mode='left_to_right')
    aspect_ratio: str | Any = Field(None, alias='aspectRatio', union_mode='left_to_right')
    external_id: str | Any = Field(None, alias='externalId', union_mode='left_to_right')
    available_for_profile_types: list[str] | Any = Field(None, alias='availableForProfileTypes', union_mode='left_to_right')
    playback_events: PlaybackEvents2 | Any = Field(None, alias='playbackEvents', union_mode='left_to_right')
    embeddable: str | Any = Field(default=None, union_mode='left_to_right')
    copyright: str | Any = Field(default=None, union_mode='left_to_right')
    add_ons: list[str] | Any = Field(None, alias='addOns', union_mode='left_to_right')
    regional_audio_exclude_languages: list[Any] | Any = Field(None, alias='regionalAudioExcludeLanguages', union_mode='left_to_right')
    regional_text_exclude_languages: list[Any] | Any = Field(None, alias='regionalTextExcludeLanguages', union_mode='left_to_right')
    original_release_year: int | Any = Field(None, alias='originalReleaseYear', union_mode='left_to_right')
    tmsseries_id: str | Any = Field(None, alias='tmsseriesID', union_mode='left_to_right')
    tmsprogram_id: str | Any = Field(None, alias='tmsprogramID', union_mode='left_to_right')
    is_content_accessible_in_can: bool | Any = Field(None, alias='isContentAccessibleInCAN', union_mode='left_to_right')
    thumbnail_sheet_set: list[ThumbnailSheetSetItem] | Any = Field(None, alias='thumbnailSheetSet', union_mode='left_to_right')
    v_tag: str | Any = Field(None, alias='vTag', union_mode='left_to_right')
    is_product_placement: bool | Any = Field(None, alias='isProductPlacement', union_mode='left_to_right')
    brand_slug: str | Any = Field(None, alias='brandSlug', union_mode='left_to_right')
    is_movie_available: bool | Any = Field(None, alias='isMovieAvailable', union_mode='left_to_right')

class RegionalRating3(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    region: str | Any = Field(default=None, union_mode='left_to_right')
    rating: str | Any = Field(default=None, union_mode='left_to_right')
    disclaimer: Any | None = None
    secondary_descriptors: str | Any = Field(None, alias='secondaryDescriptors', union_mode='left_to_right')
    subratings: list[Subrating] | Any = Field(default=None, union_mode='left_to_right')
    consumer_advice: Any | None = Field(None, alias='consumerAdvice')
    rating_icon: Any | None = Field(None, alias='ratingIcon')

class PlaybackEvents3(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    end_credit_chapter_time_ms: Any | None = Field(None, alias='endCreditChapterTimeMs')
    preview_start_time_ms: Any | None = Field(None, alias='previewStartTimeMs')
    preview_end_time_ms: Any | None = Field(None, alias='previewEndTimeMs')
    open_credit_end_time_ms: Any | None = Field(None, alias='openCreditEndTimeMs')
    open_credit_start_time: Any | None = Field(None, alias='openCreditStartTime')

class TrailerContent1(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    genre: str | Any = Field(default=None, union_mode='left_to_right')
    status: str | Any = Field(default=None, union_mode='left_to_right')
    field_first_ingest_date: str | Any = Field(None, alias='_firstIngestDate', union_mode='left_to_right')
    expired: bool | Any = Field(default=None, union_mode='left_to_right')
    show_page_url: str | Any = Field(None, alias='showPageUrl', union_mode='left_to_right')
    cbs_show_id: int | Any = Field(None, alias='cbsShowId', union_mode='left_to_right')
    primary_category: str | Any = Field(None, alias='primaryCategory', union_mode='left_to_right')
    primary_category_name: str | Any = Field(None, alias='primaryCategoryName', union_mode='left_to_right')
    edit_date: int | Any = Field(None, alias='editDate', union_mode='left_to_right')
    field_edit_date: str | Any = Field(None, alias='_editDate', union_mode='left_to_right')
    field_last_modified_date: str | Any = Field(None, alias='_lastModifiedDate', union_mode='left_to_right')
    ingest_date: int | Any = Field(None, alias='ingestDate', union_mode='left_to_right')
    air_date: int | Any = Field(None, alias='airDate', union_mode='left_to_right')
    description: str | Any = Field(default=None, union_mode='left_to_right')
    short_description: str | Any = Field(None, alias='shortDescription', union_mode='left_to_right')
    pub_date: int | Any = Field(None, alias='pubDate', union_mode='left_to_right')
    label: str | Any = Field(default=None, union_mode='left_to_right')
    video_page_url: str | Any = Field(None, alias='videoPageUrl', union_mode='left_to_right')
    url: str | Any = Field(default=None, union_mode='left_to_right')
    asset_type: str | Any = Field(None, alias='assetType', union_mode='left_to_right')
    first_ingest_date: int | Any = Field(None, alias='firstIngestDate', union_mode='left_to_right')
    category: str | Any = Field(default=None, union_mode='left_to_right')
    top_level_category: str | Any = Field(None, alias='topLevelCategory', union_mode='left_to_right')
    full_episode: bool | Any = Field(None, alias='fullEpisode', union_mode='left_to_right')
    exclusive: bool | Any = Field(default=None, union_mode='left_to_right')
    content_id: str | Any = Field(None, alias='contentId', union_mode='left_to_right')
    title: str | Any = Field(default=None, union_mode='left_to_right')
    field_ingest_date: str | Any = Field(None, alias='_ingestDate', union_mode='left_to_right')
    episode_num: str | Any = Field(None, alias='episodeNum', union_mode='left_to_right')
    field_pub_date: str | Any = Field(None, alias='_pubDate', union_mode='left_to_right')
    season_num: str | Any = Field(None, alias='seasonNum', union_mode='left_to_right')
    brand: str | Any = Field(default=None, union_mode='left_to_right')
    child_content_id: str | Any = Field(None, alias='childContentId', union_mode='left_to_right')
    sizzle_id: str | Any = Field(None, alias='sizzleId', union_mode='left_to_right')
    pid: UUID | str | Any = Field(default=None, union_mode='left_to_right')
    series_title: str | Any = Field(None, alias='seriesTitle', union_mode='left_to_right')
    field_air_date: str | Any = Field(None, alias='_airDate', union_mode='left_to_right')
    duration: int | Any = Field(default=None, union_mode='left_to_right')
    last_modified_date: int | Any = Field(None, alias='lastModifiedDate', union_mode='left_to_right')
    rating: str | Any = Field(default=None, union_mode='left_to_right')
    device_type: str | Any = Field(None, alias='deviceType', union_mode='left_to_right')
    thumbnail: str | Any = Field(default=None, union_mode='left_to_right')
    amazon_esturl: str | Any = Field(None, alias='amazonESTURL', union_mode='left_to_right')
    itunes_esturl: str | Any = Field(None, alias='itunesESTURL', union_mode='left_to_right')
    streaming_url: str | Any = Field(None, alias='streamingUrl', union_mode='left_to_right')
    expiration_date: int | Any = Field(None, alias='expirationDate', union_mode='left_to_right')
    field_expiration_date: str | Any = Field(None, alias='_expirationDate', union_mode='left_to_right')
    field_pub_date_iso: AwareDatetime | Any = Field(None, alias='_pubDateISO', union_mode='left_to_right')
    field_air_date_iso: AwareDatetime | Any = Field(None, alias='_airDateISO', union_mode='left_to_right')
    player_loc_url: str | Any = Field(None, alias='playerLocUrl', union_mode='left_to_right')
    subscription_level: str | Any = Field(None, alias='subscriptionLevel', union_mode='left_to_right')
    media_available_date: AwareDatetime | Any = Field(None, alias='mediaAvailableDate', union_mode='left_to_right')
    media_available_date_epoch: int | Any = Field(None, alias='mediaAvailableDateEpoch', union_mode='left_to_right')
    closed_caption_url: str | Any = Field(None, alias='closedCaptionUrl', union_mode='left_to_right')
    is_live: bool | Any = Field(None, alias='isLive', union_mode='left_to_right')
    cms_account_id: str | Any = Field(None, alias='cmsAccountId', union_mode='left_to_right')
    apple_watch_list_show_key: str | Any = Field(None, alias='appleWatchListShowKey', union_mode='left_to_right')
    is_protected: bool | Any = Field(None, alias='isProtected', union_mode='left_to_right')
    media_type: str | Any = Field(None, alias='mediaType', union_mode='left_to_right')
    exclude_nielsen_tracking: bool | Any = Field(None, alias='excludeNielsenTracking', union_mode='left_to_right')
    end_credits_chapter_time: str | Any = Field(None, alias='endCreditsChapterTime', union_mode='left_to_right')
    thumbnail_set: list[ThumbnailSetItem] | Any = Field(None, alias='thumbnailSet', union_mode='left_to_right')
    download_country_set: list[DownloadCountrySetItem] | Any = Field(None, alias='downloadCountrySet', union_mode='left_to_right')
    regional_ratings: list[RegionalRating3] | Any = Field(None, alias='regionalRatings', union_mode='left_to_right')
    premium_features: list[str] | Any = Field(None, alias='premiumFeatures', union_mode='left_to_right')
    video_properties: list[str] | Any = Field(None, alias='videoProperties', union_mode='left_to_right')
    aspect_ratio: str | Any = Field(None, alias='aspectRatio', union_mode='left_to_right')
    external_id: str | Any = Field(None, alias='externalId', union_mode='left_to_right')
    available_for_profile_types: list[str] | Any = Field(None, alias='availableForProfileTypes', union_mode='left_to_right')
    playback_events: PlaybackEvents3 | Any = Field(None, alias='playbackEvents', union_mode='left_to_right')
    embeddable: str | Any = Field(default=None, union_mode='left_to_right')
    copyright: str | Any = Field(default=None, union_mode='left_to_right')
    add_ons: list[str] | Any = Field(None, alias='addOns', union_mode='left_to_right')
    regional_audio_exclude_languages: list[Any] | Any = Field(None, alias='regionalAudioExcludeLanguages', union_mode='left_to_right')
    regional_text_exclude_languages: list[Any] | Any = Field(None, alias='regionalTextExcludeLanguages', union_mode='left_to_right')
    original_release_year: int | Any = Field(None, alias='originalReleaseYear', union_mode='left_to_right')
    tmsseries_id: str | Any = Field(None, alias='tmsseriesID', union_mode='left_to_right')
    tmsprogram_id: str | Any = Field(None, alias='tmsprogramID', union_mode='left_to_right')
    is_content_accessible_in_can: bool | Any = Field(None, alias='isContentAccessibleInCAN', union_mode='left_to_right')
    thumbnail_sheet_set: list[ThumbnailSheetSetItem] | Any = Field(None, alias='thumbnailSheetSet', union_mode='left_to_right')
    v_tag: str | Any = Field(None, alias='vTag', union_mode='left_to_right')
    is_product_placement: bool | Any = Field(None, alias='isProductPlacement', union_mode='left_to_right')
    brand_slug: str | Any = Field(None, alias='brandSlug', union_mode='left_to_right')

class AvailableVideoSeason1(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    season_num: str | Any = Field(None, alias='seasonNum', union_mode='left_to_right')
    total_count: int | Any = Field(None, alias='totalCount', union_mode='left_to_right')
    premium_count: int | Any = Field(None, alias='premiumCount', union_mode='left_to_right')
    clips_count: int | Any = Field(None, alias='clipsCount', union_mode='left_to_right')
    delay_count: int | Any = Field(None, alias='delayCount', union_mode='left_to_right')
    season_premiere_date: str | Any = Field(None, alias='seasonPremiereDate', union_mode='left_to_right')
    season_premiere_date_epoch: int | Any = Field(None, alias='seasonPremiereDateEpoch', union_mode='left_to_right')
    season_finale_date: Any | None = Field(None, alias='seasonFinaleDate')
    season_finale_date_epoch: Any | None = Field(None, alias='seasonFinaleDateEpoch')

class Button(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    label: str | Any = Field(default=None, union_mode='left_to_right')
    season: int | Any = Field(default=None, union_mode='left_to_right')
    episode: int | Any = Field(default=None, union_mode='left_to_right')
    url: str | Any = Field(default=None, union_mode='left_to_right')
    play: bool | Any = Field(default=None, union_mode='left_to_right')

class RegionalRating4(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    region: str | Any = Field(default=None, union_mode='left_to_right')
    rating: str | Any = Field(default=None, union_mode='left_to_right')
    disclaimer: Any | None = None
    secondary_descriptors: Any | None = Field(None, alias='secondaryDescriptors')
    subratings: Any | None = None
    consumer_advice: Any | None = Field(None, alias='consumerAdvice')
    rating_icon: Any | None = Field(None, alias='ratingIcon')

class ContentCanVideo(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    genre: str | Any = Field(default=None, union_mode='left_to_right')
    status: str | Any = Field(default=None, union_mode='left_to_right')
    field_first_ingest_date: str | Any = Field(None, alias='_firstIngestDate', union_mode='left_to_right')
    expired: bool | Any = Field(default=None, union_mode='left_to_right')
    show_page_url: str | Any = Field(None, alias='showPageUrl', union_mode='left_to_right')
    cbs_show_id: int | Any = Field(None, alias='cbsShowId', union_mode='left_to_right')
    primary_category: str | Any = Field(None, alias='primaryCategory', union_mode='left_to_right')
    primary_category_name: str | Any = Field(None, alias='primaryCategoryName', union_mode='left_to_right')
    edit_date: int | Any = Field(None, alias='editDate', union_mode='left_to_right')
    field_edit_date: str | Any = Field(None, alias='_editDate', union_mode='left_to_right')
    field_last_modified_date: str | Any = Field(None, alias='_lastModifiedDate', union_mode='left_to_right')
    ingest_date: int | Any = Field(None, alias='ingestDate', union_mode='left_to_right')
    air_date: int | Any = Field(None, alias='airDate', union_mode='left_to_right')
    description: str | Any = Field(default=None, union_mode='left_to_right')
    short_description: str | Any = Field(None, alias='shortDescription', union_mode='left_to_right')
    pub_date: int | Any = Field(None, alias='pubDate', union_mode='left_to_right')
    label: str | Any = Field(default=None, union_mode='left_to_right')
    url: str | Any = Field(default=None, union_mode='left_to_right')
    asset_type: str | Any = Field(None, alias='assetType', union_mode='left_to_right')
    first_ingest_date: int | Any = Field(None, alias='firstIngestDate', union_mode='left_to_right')
    category: str | Any = Field(default=None, union_mode='left_to_right')
    top_level_category: str | Any = Field(None, alias='topLevelCategory', union_mode='left_to_right')
    full_episode: bool | Any = Field(None, alias='fullEpisode', union_mode='left_to_right')
    exclusive: bool | Any = Field(default=None, union_mode='left_to_right')
    content_id: UUID | Any = Field(None, alias='contentId', union_mode='left_to_right')
    title: str | Any = Field(default=None, union_mode='left_to_right')
    field_ingest_date: str | Any = Field(None, alias='_ingestDate', union_mode='left_to_right')
    episode_num: str | Any = Field(None, alias='episodeNum', union_mode='left_to_right')
    field_pub_date: str | Any = Field(None, alias='_pubDate', union_mode='left_to_right')
    season_num: str | Any = Field(None, alias='seasonNum', union_mode='left_to_right')
    brand: str | Any = Field(default=None, union_mode='left_to_right')
    child_content_id: str | Any = Field(None, alias='childContentId', union_mode='left_to_right')
    sizzle_id: str | Any = Field(None, alias='sizzleId', union_mode='left_to_right')
    series_title: str | Any = Field(None, alias='seriesTitle', union_mode='left_to_right')
    field_air_date: str | Any = Field(None, alias='_airDate', union_mode='left_to_right')
    duration: int | Any = Field(default=None, union_mode='left_to_right')
    last_modified_date: int | Any = Field(None, alias='lastModifiedDate', union_mode='left_to_right')
    rating: str | Any = Field(default=None, union_mode='left_to_right')
    device_type: str | Any = Field(None, alias='deviceType', union_mode='left_to_right')
    thumbnail: str | Any = Field(default=None, union_mode='left_to_right')
    amazon_esturl: str | Any = Field(None, alias='amazonESTURL', union_mode='left_to_right')
    itunes_esturl: str | Any = Field(None, alias='itunesESTURL', union_mode='left_to_right')
    expiration_date: int | Any = Field(None, alias='expirationDate', union_mode='left_to_right')
    field_expiration_date: str | Any = Field(None, alias='_expirationDate', union_mode='left_to_right')
    field_pub_date_iso: AwareDatetime | Any = Field(None, alias='_pubDateISO', union_mode='left_to_right')
    field_air_date_iso: AwareDatetime | Any = Field(None, alias='_airDateISO', union_mode='left_to_right')
    subscription_level: str | Any = Field(None, alias='subscriptionLevel', union_mode='left_to_right')
    media_available_date: AwareDatetime | Any = Field(None, alias='mediaAvailableDate', union_mode='left_to_right')
    media_available_date_epoch: int | Any = Field(None, alias='mediaAvailableDateEpoch', union_mode='left_to_right')
    is_live: bool | Any = Field(None, alias='isLive', union_mode='left_to_right')
    cms_account_id: str | Any = Field(None, alias='cmsAccountId', union_mode='left_to_right')
    apple_watch_list_show_key: str | Any = Field(None, alias='appleWatchListShowKey', union_mode='left_to_right')
    is_protected: bool | Any = Field(None, alias='isProtected', union_mode='left_to_right')
    media_type: str | Any = Field(None, alias='mediaType', union_mode='left_to_right')
    exclude_nielsen_tracking: bool | Any = Field(None, alias='excludeNielsenTracking', union_mode='left_to_right')
    end_credits_chapter_time: str | Any = Field(None, alias='endCreditsChapterTime', union_mode='left_to_right')
    thumbnail_set: list[ThumbnailSetItem] | Any = Field(None, alias='thumbnailSet', union_mode='left_to_right')
    download_country_set: list[Any] | Any = Field(None, alias='downloadCountrySet', union_mode='left_to_right')
    regional_ratings: list[RegionalRating4] | Any = Field(None, alias='regionalRatings', union_mode='left_to_right')
    premium_features: list[str] | Any = Field(None, alias='premiumFeatures', union_mode='left_to_right')
    video_properties: list[str] | Any = Field(None, alias='videoProperties', union_mode='left_to_right')
    aspect_ratio: str | Any = Field(None, alias='aspectRatio', union_mode='left_to_right')
    daistream_key: str | Any = Field(None, alias='daistreamKey', union_mode='left_to_right')
    playback_events: PlaybackEvents3 | Any = Field(None, alias='playbackEvents', union_mode='left_to_right')
    embeddable: str | Any = Field(default=None, union_mode='left_to_right')
    copyright: str | Any = Field(default=None, union_mode='left_to_right')
    add_ons: list[Any] | Any = Field(None, alias='addOns', union_mode='left_to_right')
    regional_audio_exclude_languages: list[Any] | Any = Field(None, alias='regionalAudioExcludeLanguages', union_mode='left_to_right')
    regional_text_exclude_languages: list[Any] | Any = Field(None, alias='regionalTextExcludeLanguages', union_mode='left_to_right')
    original_release_year: int | Any = Field(None, alias='originalReleaseYear', union_mode='left_to_right')
    tmsseries_id: str | Any = Field(None, alias='tmsseriesID', union_mode='left_to_right')
    tmsprogram_id: str | Any = Field(None, alias='tmsprogramID', union_mode='left_to_right')
    is_content_accessible_in_can: bool | Any = Field(None, alias='isContentAccessibleInCAN', union_mode='left_to_right')
    thumbnail_sheet_set: list[Any] | Any = Field(None, alias='thumbnailSheetSet', union_mode='left_to_right')
    v_tag: str | Any = Field(None, alias='vTag', union_mode='left_to_right')
    is_product_placement: bool | Any = Field(None, alias='isProductPlacement', union_mode='left_to_right')

class Datum(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    title: str | Any = Field(default=None, union_mode='left_to_right')
    description: str | Any = Field(default=None, union_mode='left_to_right')
    slug: str | Any = Field(default=None, union_mode='left_to_right')
    brand_id: str | Any = Field(None, alias='brandId', union_mode='left_to_right')
    brand_slug: str | Any = Field(None, alias='brandSlug', union_mode='left_to_right')
    page_type: str | Any = Field(None, alias='pageType', union_mode='left_to_right')
    show_path: str | Any = Field(None, alias='showPath', union_mode='left_to_right')
    movie_page_url: str | Any = Field(None, alias='moviePageUrl', union_mode='left_to_right')
    content_type: str | Any = Field(None, alias='contentType', union_mode='left_to_right')
    href: str | Any = Field(default=None, union_mode='left_to_right')
    thumb: str | Any = Field(default=None, union_mode='left_to_right')
    brand_logo: str | Any = Field(None, alias='brandLogo', union_mode='left_to_right')
    top_ten_badge: Any | None = Field(None, alias='topTenBadge')
    action_text: str | Any = Field(None, alias='actionText', union_mode='left_to_right')
    po_copy: str | Any = Field(None, alias='poCopy', union_mode='left_to_right')
    filepath_logo_regular_image: str | Any = Field(None, alias='filepathLogoRegularImage', union_mode='left_to_right')
    logo_image: str | Any = Field(None, alias='logoImage', union_mode='left_to_right')
    background_image: str | Any = Field(None, alias='backgroundImage', union_mode='left_to_right')
    background_mobile_image: str | Any = Field(None, alias='backgroundMobileImage', union_mode='left_to_right')
    filepath_logo_compact_image: str | Any = Field(None, alias='filepathLogoCompactImage', union_mode='left_to_right')
    filepath_background_hero_image: str | Any = Field(None, alias='filepathBackgroundHeroImage', union_mode='left_to_right')
    filepath_mobile_web_image: str | Any = Field(None, alias='filepathMobileWebImage', union_mode='left_to_right')
    filepath_promo_tile_poster_image: str | Any = Field(None, alias='filepathPromoTilePosterImage', union_mode='left_to_right')
    filepath_promo_tile_landscape_image: str | Any = Field(None, alias='filepathPromoTileLandscapeImage', union_mode='left_to_right')
    content_id_impression: int | str | Any = Field(None, alias='contentIdImpression', union_mode='left_to_right')
    position: int | Any = Field(default=None, union_mode='left_to_right')
    rank_model: Any | None = Field(None, alias='rankModel')
    cms_id: int | str | Any = Field(None, alias='cmsId', union_mode='left_to_right')
    content: Content | Any = Field(default=None, union_mode='left_to_right')
    id: int | str | Any = Field(default=None, union_mode='left_to_right')
    content_id: int | str | Any = Field(None, alias='contentId', union_mode='left_to_right')
    alt: str | Any = Field(default=None, union_mode='left_to_right')
    tune_in_time: str | Any = Field(None, alias='tuneInTime', union_mode='left_to_right')
    category: str | Any = Field(default=None, union_mode='left_to_right')
    is_listing_live: bool | Any = Field(None, alias='isListingLive', union_mode='left_to_right')
    show: Any | None = None
    pvr_model: str | Any = Field(None, alias='pvrModel', union_mode='left_to_right')
    item_pem: ItemPem | Any = Field(None, alias='itemPEM', union_mode='left_to_right')
    bundle_locked: bool | Any = Field(None, alias='bundleLocked', union_mode='left_to_right')
    badge_label: bool | str | Any = Field(None, alias='badgeLabel', union_mode='left_to_right')
    aa_link: str | Any = Field(None, alias='aaLink', union_mode='left_to_right')
    impression: str | Any = Field(default=None, union_mode='left_to_right')
    promo_tile: bool | Any = Field(None, alias='promoTile', union_mode='left_to_right')
    promo_icon: str | Any = Field(None, alias='promoIcon', union_mode='left_to_right')
    cta_line1: str | Any = Field(None, alias='ctaLine1', union_mode='left_to_right')
    cta_line2: str | Any = Field(None, alias='ctaLine2', union_mode='left_to_right')
    cta_text: str | Any = Field(None, alias='ctaText', union_mode='left_to_right')
    deep_link_url: str | Any = Field(None, alias='deepLinkUrl', union_mode='left_to_right')
    hub_id: int | Any = Field(None, alias='hubId', union_mode='left_to_right')
    content_locked: int | str | Any = Field(None, alias='contentLocked', union_mode='left_to_right')
    is_user_subscriber: bool | Any = Field(None, alias='isUserSubscriber', union_mode='left_to_right')
    is_user_registered: bool | Any = Field(None, alias='isUserRegistered', union_mode='left_to_right')
    brand: str | Any = Field(default=None, union_mode='left_to_right')
    data_tracking: str | Any = Field(None, alias='dataTracking', union_mode='left_to_right')
    is_movie: bool | Any = Field(None, alias='isMovie', union_mode='left_to_right')
    label: str | Any = Field(default=None, union_mode='left_to_right')
    genre: str | Any = Field(default=None, union_mode='left_to_right')
    show_series_id: int | str | Any = Field(None, alias='showSeriesId', union_mode='left_to_right')
    series_id: int | str | Any = Field(None, alias='seriesId', union_mode='left_to_right')
    content_id_1: UUID | str | Any = Field(None, alias='content_id', union_mode='left_to_right')
    orientation: str | Any = Field(default=None, union_mode='left_to_right')
    movie_id: int | str | Any = Field(None, alias='movieId', union_mode='left_to_right')
    upsell_url: str | Any = Field(None, alias='upsellUrl', union_mode='left_to_right')
    lock_icon: str | Any = Field(None, alias='lockIcon', union_mode='left_to_right')
    show_movie_id: str | Any = Field(None, alias='showMovieId', union_mode='left_to_right')
    action_url: str | Any = Field(None, alias='actionUrl', union_mode='left_to_right')
    series_title: str | Any = Field(None, alias='seriesTitle', union_mode='left_to_right')
    episode_title: str | Any = Field(None, alias='episodeTitle', union_mode='left_to_right')
    episode_id: str | Any = Field(None, alias='episodeId', union_mode='left_to_right')
    season_number: str | Any = Field(None, alias='seasonNumber', union_mode='left_to_right')
    rating: str | Any = Field(default=None, union_mode='left_to_right')
    rating_icon: str | Any = Field(None, alias='ratingIcon', union_mode='left_to_right')
    is_hub_carousel: bool | Any = Field(None, alias='isHubCarousel', union_mode='left_to_right')
    video_id: str | Any = Field(None, alias='videoId', union_mode='left_to_right')
    available_date: str | Any = Field(None, alias='availableDate', union_mode='left_to_right')
    show_countdown_timer: bool | Any = Field(None, alias='showCountdownTimer', union_mode='left_to_right')
    start_timestamp: int | str | Any = Field(None, alias='startTimestamp', union_mode='left_to_right')
    end_timestamp: str | Any = Field(None, alias='endTimestamp', union_mode='left_to_right')
    stream_start_timestamp: int | str | Any = Field(None, alias='streamStartTimestamp', union_mode='left_to_right')
    stream_end_timestamp: str | Any = Field(None, alias='streamEndTimestamp', union_mode='left_to_right')
    thumbnail: str | Any = Field(default=None, union_mode='left_to_right')
    sizzle_content_id: str | Any = Field(None, alias='sizzleContentId', union_mode='left_to_right')
    video_preview_url: str | Any = Field(None, alias='videoPreviewURL', union_mode='left_to_right')
    video_preview_id: str | Any = Field(None, alias='videoPreviewId', union_mode='left_to_right')
    show_or_movie: str | Any = Field(None, alias='showOrMovie', union_mode='left_to_right')
    notify_on: bool | Any = Field(None, alias='notifyOn', union_mode='left_to_right')
    allow_my_list_controls: bool | Any = Field(None, alias='allowMyListControls', union_mode='left_to_right')
    watch_list_cta_content: WatchListCtaContent | Any = Field(None, alias='watchListCtaContent', union_mode='left_to_right')
    cast_names: str | Any = Field(None, alias='castNames', union_mode='left_to_right')
    display_item_title: bool | Any = Field(None, alias='displayItemTitle', union_mode='left_to_right')
    is_user_kid_profile: str | Any = Field(None, alias='isUserKidProfile', union_mode='left_to_right')
    is_content_accessible_in_cms: bool | Any = Field(None, alias='isContentAccessibleInCMS', union_mode='left_to_right')
    show_title: str | Any = Field(None, alias='showTitle', union_mode='left_to_right')
    about: str | Any = Field(default=None, union_mode='left_to_right')
    movie_content: MovieContent1 | Any = Field(None, alias='movieContent', union_mode='left_to_right')
    trailer_content: TrailerContent1 | Any = Field(None, alias='trailerContent', union_mode='left_to_right')
    show_series_title: str | Any = Field(None, alias='showSeriesTitle', union_mode='left_to_right')
    title_slug: str | Any = Field(None, alias='titleSlug', union_mode='left_to_right')
    brand_name: str | Any = Field(None, alias='brandName', union_mode='left_to_right')
    num_seasons: int | str | Any = Field(None, alias='numSeasons', union_mode='left_to_right')
    carousel_content_type: str | Any = Field(None, alias='carouselContentType', union_mode='left_to_right')
    poster: str | Any = Field(default=None, union_mode='left_to_right')
    content_notification_add_action_url: str | Any = Field(None, alias='contentNotificationAddActionUrl', union_mode='left_to_right')
    content_notification_remove_action_url: str | Any = Field(None, alias='contentNotificationRemoveActionUrl', union_mode='left_to_right')
    content_my_list_add_action_url: str | Any = Field(None, alias='contentMyListAddActionUrl', union_mode='left_to_right')
    content_my_list_remove_action_url: str | Any = Field(None, alias='contentMyListRemoveActionUrl', union_mode='left_to_right')
    has_content_highlight: bool | Any = Field(None, alias='hasContentHighlight', union_mode='left_to_right')
    show_id: int | Any = Field(None, alias='showId', union_mode='left_to_right')
    carousel_type: str | Any = Field(None, alias='carouselType', union_mode='left_to_right')
    video_content_id: str | Any = Field(None, alias='videoContentId', union_mode='left_to_right')
    time_stamp: str | Any = Field(None, alias='timeStamp', union_mode='left_to_right')
    is_seasonless: bool | Any = Field(None, alias='isSeasonless', union_mode='left_to_right')
    is_episodeless: bool | Any = Field(None, alias='isEpisodeless', union_mode='left_to_right')
    season_counts: str | Any = Field(None, alias='seasonCounts', union_mode='left_to_right')
    premiere_date: str | Any = Field(None, alias='premiereDate', union_mode='left_to_right')
    available_video_seasons: list[AvailableVideoSeason1] | Any = Field(None, alias='availableVideoSeasons', union_mode='left_to_right')
    button: Button | Any = Field(default=None, union_mode='left_to_right')
    logo: str | Any = Field(default=None, union_mode='left_to_right')
    title_text: str | Any = Field(None, alias='titleText', union_mode='left_to_right')
    movie_duration: str | Any = Field(None, alias='movieDuration', union_mode='left_to_right')
    movie_rating: str | Any = Field(None, alias='movieRating', union_mode='left_to_right')
    url: str | Any = Field(default=None, union_mode='left_to_right')
    is_live: bool | Any = Field(None, alias='isLive', union_mode='left_to_right')
    channel_slug: str | Any = Field(None, alias='channelSlug', union_mode='left_to_right')
    stream_start_time_formatted: AwareDatetime | Any = Field(None, alias='streamStartTimeFormatted', union_mode='left_to_right')
    elapsed_time: AwareDatetime | str | Any = Field(None, alias='elapsedTime', union_mode='left_to_right')
    content_can_video: ContentCanVideo | Any = Field(None, alias='contentCANVideo', union_mode='left_to_right')
    status: str | Any = Field(default=None, union_mode='left_to_right')
    show_id_1: int | Any = Field(None, alias='show_id', union_mode='left_to_right')
    duration: str | Any = Field(default=None, union_mode='left_to_right')
    schedule_badge: bool | Any = Field(None, alias='scheduleBadge', union_mode='left_to_right')
    schedule_badge_text: str | Any = Field(None, alias='scheduleBadgeText', union_mode='left_to_right')
    is_multi_channel: bool | Any = Field(None, alias='isMultiChannel', union_mode='left_to_right')
    live_badge_text: str | Any = Field(None, alias='liveBadgeText', union_mode='left_to_right')
    live_tv_channel: str | Any = Field(None, alias='liveTvChannel', union_mode='left_to_right')
    station_code: str | Any = Field(None, alias='stationCode', union_mode='left_to_right')
    stream_type: str | Any = Field(None, alias='streamType', union_mode='left_to_right')
    on_now_title: str | Any = Field(None, alias='onNowTitle', union_mode='left_to_right')
    channel_logo: str | Any = Field(None, alias='channelLogo', union_mode='left_to_right')
    multi_channel_name: str | Any = Field(None, alias='multiChannelName', union_mode='left_to_right')
    locked: bool | Any = Field(default=None, union_mode='left_to_right')
    local_live_tv: bool | Any = Field(None, alias='localLiveTV', union_mode='left_to_right')
    is_upcoming: bool | Any = Field(None, alias='isUpcoming', union_mode='left_to_right')
    progress: int | float | Any = Field(default=None, union_mode='left_to_right')
    progress_text: str | Any = Field(None, alias='progressText', union_mode='left_to_right')
    channel_name: str | Any = Field(None, alias='channelName', union_mode='left_to_right')
    filepath1x1_default_image: str | Any = Field(None, alias='filepath1x1DefaultImage', union_mode='left_to_right')
    filepath1x1_focus_state_image: str | Any = Field(None, alias='filepath1x1FocusStateImage', union_mode='left_to_right')
    movie_title: str | Any = Field(None, alias='movieTitle', union_mode='left_to_right')

class Data(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    id: int | Any = Field(default=None, union_mode='left_to_right')
    origin_id: int | Any = Field(None, alias='originId', union_mode='left_to_right')
    slug: str | Any = Field(default=None, union_mode='left_to_right')
    channel_name: str | Any = Field(None, alias='channelName', union_mode='left_to_right')
    description: Any | None = None
    timezone: str | Any = Field(default=None, union_mode='left_to_right')
    file_path_logo: str | Any = Field(None, alias='filePathLogo', union_mode='left_to_right')
    file_path_logo_selected: str | Any = Field(None, alias='filePathLogoSelected', union_mode='left_to_right')
    file_path_small_logo: str | Any = Field(None, alias='filePathSmallLogo', union_mode='left_to_right')
    file_path_small_logo_selected: str | Any = Field(None, alias='filePathSmallLogoSelected', union_mode='left_to_right')
    prg_svc_id: int | Any = Field(None, alias='prgSvcId', union_mode='left_to_right')
    ptv_id: Any | None = Field(None, alias='ptvId')
    city: Any | None = None
    state: Any | None = None
    postal_code: Any | None = Field(None, alias='postalCode')
    dma: Any | None = None
    display_order: int | Any = Field(None, alias='displayOrder', union_mode='left_to_right')
    filepath_fallback_image: Any | None = Field(None, alias='filepathFallbackImage')
    provider_type: str | Any = Field(None, alias='providerType', union_mode='left_to_right')
    cbs_packages: list[str] | Any = Field(None, alias='cbsPackages', union_mode='left_to_right')
    video_content_id: UUID | Any = Field(None, alias='videoContentId', union_mode='left_to_right')
    stream_type: str | Any = Field(None, alias='streamType', union_mode='left_to_right')
    display_metadata: bool | Any = Field(None, alias='displayMetadata', union_mode='left_to_right')
    promo_content_type: Any | None = Field(None, alias='promoContentType')
    promo_content_id: Any | None = Field(None, alias='promoContentId')
    promo_title: Any | None = Field(None, alias='promoTitle')
    filepath_promo_thumbnail: Any | None = Field(None, alias='filepathPromoThumbnail')
    channel_category_slugs: list[str] | Any = Field(None, alias='channelCategorySlugs', union_mode='left_to_right')
    filepath_live_end_card_image: Any | None = Field(None, alias='filepathLiveEndCardImage')
    channel_types: list[str] | Any = Field(None, alias='channelTypes', union_mode='left_to_right')
    display_style: str | Any = Field(None, alias='displayStyle', union_mode='left_to_right')
    sort_theme: str | Any = Field(None, alias='sortTheme', union_mode='left_to_right')
    current_listing: Any | None = Field(None, alias='currentListing')
    upcoming_listing: list[Any] | Any = Field(None, alias='upcomingListing', union_mode='left_to_right')
    brand: Any | None = None
    total_number_of_current_listings: int | Any = Field(None, alias='totalNumberOfCurrentListings', union_mode='left_to_right')
    total_number_of_upcoming_listings: int | Any = Field(None, alias='totalNumberOfUpcomingListings', union_mode='left_to_right')
    entitlement_codes: Any | None = Field(None, alias='entitlementCodes')
    display_count_down_timer: bool | Any = Field(None, alias='displayCountDownTimer', union_mode='left_to_right')
    required_add_ons: list[Any] | Any = Field(None, alias='requiredAddOns', union_mode='left_to_right')
    enable_dashdrm: bool | Any = Field(None, alias='enableDASHDRM', union_mode='left_to_right')
    kids_mode: bool | Any = Field(None, alias='kidsMode', union_mode='left_to_right')
    local: bool | Any = Field(default=None, union_mode='left_to_right')
    is_content_accessible_in_cms: bool | Any = Field(None, alias='isContentAccessibleInCMS', union_mode='left_to_right')

class CarouselModel(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    id: str | Any = Field(default=None, union_mode='left_to_right')
    title: str | Any = Field(default=None, union_mode='left_to_right')
    orientation: str | Any = Field(default=None, union_mode='left_to_right')
    left_arrow: str | Any = Field(None, alias='leftArrow', union_mode='left_to_right')
    right_arrow: str | Any = Field(None, alias='rightArrow', union_mode='left_to_right')
    display_id: UUID | str | Any = Field(None, alias='displayId', union_mode='left_to_right')
    reco_id: UUID | str | Any = Field(None, alias='recoId', union_mode='left_to_right')
    data: list[Datum] | Data | Any = Field(default=None, union_mode='left_to_right')
    carousel_id: UUID | str | Any = Field(None, alias='carouselId', union_mode='left_to_right')
    model: str | Any = Field(default=None, union_mode='left_to_right')
    rank_model: str | Any = Field(default=None, union_mode='left_to_right')
    pvr_model: str | Any = Field(default=None, union_mode='left_to_right')
    data_ci: str | Any = Field(None, alias='dataCi', union_mode='left_to_right')
    carousel_presentation_style: str | Any = Field(None, alias='carouselPresentationStyle', union_mode='left_to_right')
    is_content_highlight_enabled: bool | Any = Field(None, alias='isContentHighlightEnabled', union_mode='left_to_right')
    total: int | Any = Field(default=None, union_mode='left_to_right')
    include_profile_dropdown: bool | Any = Field(None, alias='includeProfileDropdown', union_mode='left_to_right')
    live_sports_data: bool | Any = Field(None, alias='liveSportsData', union_mode='left_to_right')
    display_scores_toggle: bool | Any = Field(None, alias='displayScoresToggle', union_mode='left_to_right')
    carousel_pem: Any | None = Field(None, alias='carouselPEM')
    red_dot: bool | Any = Field(None, alias='redDot', union_mode='left_to_right')
    _raw_input: Any = PrivateAttr(default=None)

    @model_validator(mode='wrap')
    @classmethod
    def _capture_raw_input(cls, data: Any, handler: ModelWrapValidatorHandler[Self]) -> Self:
        """Validate the model and keep the input it was built from."""
        model = handler(data)
        model._raw_input = data
        return model

    @property
    def raw_input(self) -> Any:
        """The input this model was validated from, as it was handed over."""
        return self._raw_input
